import { Link } from "react-router-dom";
import { FiActivity, FiCloudRain, FiCreditCard, FiCpu, FiShield, FiZap } from "react-icons/fi";

import TopNav from "../components/TopNav";

const featureCards = [
  {
    title: "Climate Risk Monitoring",
    description: "Tracks hyperlocal rainfall, heat and disruption patterns to anticipate weekly income volatility.",
    icon: FiCloudRain,
    iconBg: "bg-[#DBEEFF]",
    iconColor: "text-[#0B1120]",
  },
  {
    title: "Auto Claim Trigger",
    description: "Parametric triggers activate payouts automatically when verified climate thresholds are crossed.",
    icon: FiZap,
    iconBg: "bg-[#FFF2D7]",
    iconColor: "text-[#0B1120]",
  },
  {
    title: "AI Premium Pricing",
    description: "Fair premium recommendations are generated by machine learning risk models for each worker zone.",
    icon: FiCpu,
    iconBg: "bg-[#DFF8F1]",
    iconColor: "text-[#0B1120]",
  },
  {
    title: "Worker-First Coverage",
    description: "Designed specifically for Zomato, Swiggy, Zepto, Amazon and Blinkit delivery partners.",
    icon: FiShield,
    iconBg: "bg-[#E8ECFF]",
    iconColor: "text-[#0B1120]",
  },
  {
    title: "Dynamic Risk Signals",
    description: "Combines AQI, flood alerts and rainfall intensity into one continuously updated risk stream.",
    icon: FiActivity,
    iconBg: "bg-[#FFE7E7]",
    iconColor: "text-[#0B1120]",
  },
  {
    title: "Instant UPI Payout",
    description: "Eligible claims settle directly to UPI with transparent status tracking for every payout event.",
    icon: FiCreditCard,
    iconBg: "bg-[#E6FBF5]",
    iconColor: "text-[#0B1120]",
  },
];

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-[#F7F8FC] pb-12">
      <TopNav />

      <section className="mx-auto mt-8 max-w-6xl px-4 text-center sm:px-6">
        <p className="pulse-badge mx-auto inline-flex items-center rounded-full border border-[#E4E8F0] bg-white px-5 py-2 text-xs font-semibold tracking-[0.18em] text-[#0B1120]">
          CLIMATE + FINTECH + AI
        </p>

        <h1 className="mx-auto mt-6 max-w-4xl font-heading text-4xl font-semibold leading-tight text-[#0B1120] sm:text-5xl lg:text-6xl">
          AI-powered income protection for India&apos;s gig delivery workforce with
          <span className="text-[#F5A623]"> smarter climate-triggered cover</span>
        </h1>

        <p className="mx-auto mt-5 max-w-3xl text-base leading-7 text-[#5A6578] sm:text-lg">
          GigShield helps Zomato, Swiggy, Zepto and Amazon delivery workers protect weekly earnings when extreme
          weather disrupts routes.
        </p>

        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <Link
            to="/signup"
            className="rounded-[20px] border border-[#0B1120] bg-[#0B1120] px-6 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5"
          >
            Start Protection
          </Link>
          <Link
            to="/dashboard"
            className="rounded-[20px] border border-[#E4E8F0] bg-white px-6 py-3 text-sm font-semibold text-[#0B1120] transition hover:-translate-y-0.5"
          >
            View Dashboard
          </Link>
        </div>
      </section>

      <section className="mx-auto mt-10 grid max-w-6xl gap-4 px-4 sm:grid-cols-2 sm:px-6 lg:grid-cols-4">
        <article className="rounded-2xl border border-[#E4E8F0] bg-white p-5">
          <p className="text-sm text-[#5A6578]">Active Gig Workforce</p>
          <p className="mt-2 text-3xl font-semibold text-[#0B1120]">15M+</p>
        </article>
        <article className="rounded-2xl border border-[#E4E8F0] bg-white p-5">
          <p className="text-sm text-[#5A6578]">Avg Climate Income Loss</p>
          <p className="mt-2 text-3xl font-semibold text-[#E03E3E]">-28%</p>
        </article>
        <article className="rounded-2xl border border-[#E4E8F0] bg-white p-5">
          <p className="text-sm text-[#5A6578]">Weekly Premium</p>
          <p className="mt-2 text-3xl font-semibold text-[#F5A623]">Rs 95</p>
        </article>
        <article className="rounded-2xl border border-[#E4E8F0] bg-white p-5">
          <p className="text-sm text-[#5A6578]">Claim Trigger Time</p>
          <p className="mt-2 text-3xl font-semibold text-[#00A87A]">&lt;24h</p>
        </article>
      </section>

      <section className="mx-auto mt-10 grid max-w-6xl gap-4 px-4 sm:grid-cols-2 sm:px-6 lg:grid-cols-3">
        {featureCards.map((feature) => {
          const Icon = feature.icon;
          return (
            <article
              key={feature.title}
              className="rounded-2xl border border-[#E4E8F0] bg-white p-6 transition hover:-translate-y-0.5"
            >
              <div className={`inline-flex h-11 w-11 items-center justify-center rounded-xl ${feature.iconBg}`}>
                <Icon className={`text-xl ${feature.iconColor}`} />
              </div>
              <h2 className="mt-4 text-lg font-semibold text-[#0B1120]">{feature.title}</h2>
              <p className="mt-2 text-sm leading-6 text-[#5A6578]">{feature.description}</p>
            </article>
          );
        })}
      </section>
    </main>
  );
}
